version: "3"
services:
  daily:
    container_name: daily
    image: daily:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/daily
    restart: always
    build: .
    ports:
      - "7000:7000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/daily
    ports:
      - '27018:27017'
