version: "3"
services:
  boilerplate:
    container_name: boilerplate
    image: boilerplate:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/boilerplate
    restart: always
    build: .
    ports:
      - "7000:7000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/boilerplate
    ports:
      - '27018:27017'
